spring:
  config:
    activate:
      on-profile: local

logging:
  level:
    root: INFO
    com.yeshwanthk.agentic_url_shortener: DEBUG

server:
  port: 8082

app:
  public-base-url: ${PUBLIC_BASE_URL:http://localhost:8082}