spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    properties:
      hibernate:
        format_sql: false

logging:
  level:
    root: INFO
    org.hibernate.SQL: WARN

management:
  endpoint:
    health:
      show-details: never